site_name: Notes for Open Quantum Systems
site_url: https://openquantumsystemsnotes.com

theme:
  language: en
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: octicons/moon-24 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  favicon: images/favicon.png

  features:
    - toc.follow
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.top

  icon:
    logo: fontawesome/solid/cat
    annotation: octicons/question-24

nav:
  - About: index.md
  - Fundamentals:
    - fundamentals/index.md
    - fundamentals/quantum-states.md
  - Open Quantum Systems:
    - oqs/index.md
  - Cheatsheet: cheatsheet.md
  - Check yourself: check-yourself.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - toc
  - abbr
  - admonition
  - pymdownx.snippets
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css